import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({
    // import.meta.dirname is available after Node.js v20.11.0
    baseDirectory: import.meta.dirname,
});

const eslintConfig = [
    ...compat.config({
        extends: ['next'],
        rules: {
            'react/no-unescaped-entities': 'off',
            '@next/next/no-page-custom-font': 'off',
            'no-unused-vars': 'off',
            'no-console': 'off',
            'no-undef': 'off',
            'no-unused-expressions': 'off',
            'no-constant-condition': 'off',
            'no-async-promise-executor': 'off',
            'no-duplicate-imports': 'off',
            'no-redeclare': 'off',
            'no-shadow': 'off',
            'no-undef-init': 'off',
            'no-unused-labels': 'off',
            'no-useless-escape': 'off',
            'no-var': 'off',
            'prefer-const': 'off',
            'prefer-rest-params': 'off',
            'prefer-spread': 'off',
            'prefer-template': 'off',
            'react/jsx-uses-react': 'off',
            'react/react-in-jsx-scope': 'off',
            'react/no-children-prop': 'off',
            'react/no-unknown-property': 'off',
            'react-hooks/rules-of-hooks': 'error',
            'react-hooks/exhaustive-deps': 'warn',
            'import/no-unresolved': 'off',
            'import/extensions': 'off',
            'import/no-named-as-default': 'off',
            'import/no-named-as-default-member': 'off',
            'import/prefer-default-export': 'off',
            'import/order': 'off',
            'import/no-duplicates': 'off',
            'import/no-extraneous-dependencies': 'off',
            'import/no-mutable-exports': 'off',
            'import/no-webpack-loader-syntax': 'off',
            'import/no-anonymous-default-export': 'off',
            'import/namespace': 'off',
            'import/default': 'off',
            'import/export': 'off',
            'import/no-cycle': 'off',
            'import/no-self-import': 'off',
            'import/no-useless-path-segments': 'off',
            'import/no-relative-packages': 'off',
            'import/no-relative-parent-imports': 'off',
            'import/no-deprecated': 'off',
            'import/no-named-default': 'off',
            'import/no-unassigned-import': 'off',
            'import/no-unused-modules': 'off',
            'import/no-named-export': 'off',
            'import/no-default-export': 'off',
            'import/no-named-as-default': 'off',
            'import/no-named-as-default-member': 'off',
            'import/no-namespace': 'off',
            'import/no-absolute-path': 'off',
            'import/no-relative-packages': 'off',
            'import/no-relative-parent-imports': 'off',
            'import/no-useless-path-segments': 'off',
            'import/no-self-import': 'off',
            'import/no-cycle': 'off',
            'import/no-mutable-exports': 'off',
            'import/no-webpack-loader-syntax': 'off',
            'import/no-anonymous-default-export': 'off',
            'import/first': 'off',
            'import/exports-last': 'off',
            'import/group-exports': 'off',
            'import/max-dependencies': 'off',
            'import/no-duplicates': 'off',
            'import/no-named-default': 'off',
            'import/no-named-as-default': 'off',
            'import/no-named-as-default-member': 'off',
            'import/no-named-export': 'off',
            'import/no-default-export': 'off',
        },
    }),
];

export default eslintConfig;
