import deviceDealsTest01 from '@/public/top-deals/device-deal-test-01.png';

export const topDealsData = [
    {
        id: 1,
        order: 1,
        title: 'Apple iPhone 14 Pro - 1TB - Silver - Fully Unlocked - Excellent',
        off: '60%',
        isDeal: true,
        price: 604.76,
        img: deviceDealsTest01,
        href: '/',
    },
    {
        id: 2,
        order: 2,
        title: 'Microsoft  Type Cover for Surface Pro 3 - Black - Premium',
        isDeal: false,
        price: 60,
        img: deviceDealsTest01,
        href: '/',
    },
    {
        id: 3,
        order: 3,
        title: 'Apple iPhone 15 Pro Max - 256GB - Natural Titanium - Verizon - Premium',
        off: '33%',
        isDeal: true,
        price: 802.99,
        img: deviceDealsTest01,
        href: '/',
    },
    {
        id: 4,
        order: 4,
        title: 'Apple iPhone 15 Pro - 128GB - Blue Titanium - AT&T - Excellent',
        off: '35%',
        isDeal: true,
        price: 652.34,
        img: deviceDealsTest01,
        href: '/',
    },
    {
        id: 5,
        order: 5,
        title: 'Apple iPhone 15 Pro Max - 256GB - Natural Titanium - Verizon - Excellent',
        off: '36%',
        isDeal: true,
        price: 762.79,
        img: deviceDealsTest01,
        href: '/',
    },
];
